version: '3.7'
services:
  web:
    build: ./app
    # image: mikeryan56/test-api:19.1-beta-1
    image: mikeryan56/fastapi_example:latest
    ports:
    - "52002:5000"
    volumes:
    - .:/code
    environment:
      VIRTUAL_HOST: test-api.devsetgo.com
      LETSENCRYPT_HOST: test-api.devsetgo.com
  # deploy:
  #    replicas: 2
  #    resources:
  #      limits:
  #        cpus: "2"
  #        memory: 100M
#      restart_policy:
#        condition: always