version: '3'
# networks:
#   web:
#     external: true

services:
  test-api:
    # build: ./app
    # image: mikeryan56/test-api:test
    image: mikeryan56/test-api:latest
    ports:
    - "5000"
    volumes:
    - .:/code
    environment:
      # This is used to determin if .env or other external config is used. True is for a .env file and false for docker enviroment
      # option: dotenv, docker
      USE_ENV: docker
      # Application information
      APP_VERSION: '20.03.08'
      OWNER: 'Your Name'
      WEBSITE: https://your.domain.com/support
      # Demo settings
      CREATE_SAMPLE_DATA: True
      NUMBER_TASKS: 1000
      NUMBER_USERS: 1000
      # Cofigurations
      HOST_DOMAIN: https://your.domain.com
      #prd for production or dev for development
      RELEASE_ENV: dev
      # Turn HTTPS Middleware on (True) or off (False)
      HTTPS_ON: True
      SQLALCHEMY_DATABASE_URI: sqlite:///sqlite_db/api.db
      SECRET_KEY: 'a-secret-key'
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 10080
      # Loguru settings
      LOGURU_RETENTION: 10 days
      LOGURU_ROTATION: 100 MB
      # Leave intact for license
      CREATED_BY: 'Mike Ryan'
      LICENSE_TYPE: 'MIT'
      LICENSE_LINK: https://github.com/devsetgo/test-api/blob/master/LICENSE

    #if using traefik
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.test-api.rule=Host(`test-api.devsetgo.com`)"
    - "traefik.http.routers.test-api.entrypoints=websecure"
    - "traefik.http.routers.test-api.tls.certresolver=mytlschallenge"
    # networks:
    #   - web
    # restart:
    #   - "always"
    # healthcheck:
    #   test: curl --fail -s http://localhost:5000/ || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
  # deploy:
  #    replicas: 2
  #    resources:
  #      limits:
  #        cpus: "2"
  #        memory: 100M
