name: DockerBuild-Master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd app
        pip install -r requirements/dev.txt
    - name: Test with pytest
      run: |
        cd app
        python3 -m pytest -v -s
    - name: docker-build
      env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      run: |
        ls -l
        eccho 'Docker Login'
        docker login -u $DOCKER_USERNAME - $DOCKER_PASSWORD
        cd app
        date=$(date '+%Y-%m-%d')
        eccho 'Docker Build'
        echo docker build . -t mikeryan56/testapi:$date
        # date=$(date '+%Y-%m-%d')
        # docker tag

      # uses: elgohr/Publish-Docker-Github-Action@master
      # with:
      #   name: mikeryan56/testapi
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
      #   dockerfile: /app/dockerfile


