name: DockerBuild-Master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.7'] #, '3.7']
    steps:
    - uses: actions/checkout@master
    - name: Python ${{ matrix.python }} version
      uses: actions/setup-python@v1
      with:
          python-version: ${{ matrix.python }}
          architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd app
        pip install -r requirements/dev.txt
    - name: Test with pytest
      run: |
        cd app
        python3 -m pytest -v -s
    - name: docker-build
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        CAL_VER: $(date '+%Y-%m-%d')
      run: |
        ls -l
        echo 'Docker Login'
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        cd app
        # date=$(date '+%Y-%m-%d')
        echo 'Docker Build'
        docker build . -t mikeryan56/testapi:$CAL_VER-dev


      # uses: elgohr/Publish-Docker-Github-Action@master
      # with:
      #   name: mikeryan56/testapi
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
      #   dockerfile: /app/dockerfile


