name: Latest Changes
on:
  pull_request_target:
    branches:
      - 'release-candidate'
    types:
      - closed
jobs:
  latest-changes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: tiangolo/latest-changes:0.0.1
        with:
          token: ${{ secrets.RELEASE_NOTES }}
          latest_changes_file: ./latest-changes.md
          latest_changes_header: '## Merged PRs\n\n'
          debug_logs: true